database connection with register employees form and changes in style…
BrightCoders-Institute/BCDIC22-RoR-reloj-checador-team2 pull request #27
Opened 2023-01-25 21:31 UTC by DiegoMoralesBravo

# Description

What did you implement/Why did you implement this:

- Employee register form created
- Database connection between register employee form and employee table

## Test

* Move to /employees/new path or click in the add employee button in the /employee path
* Fill the form and submit
* Check the employee's table for the employee created

## Screenshots

![image](https://user-images.githubusercontent.com/84949558/214695253-8c02d1d8-3b79-41f3-8bc4-91e06f0dd735.png)

2023-01-25 21:48 UTC, AangelF approved these changes

2023-01-25 22:29 UTC, DiegoCoronaBarragan approved these changes
LGTM

2023-01-25 22:31 UTC, Yaxkin121 approved these changes
LGTM

2023-01-25 22:32 UTC, EverardoAlcarazBaltazar approved these changes
LGTM

2023-01-25 22:51 UTC, oscaregr approved these changes

2023-01-26 00:08 UTC, juperameza requested changes

2023-01-26 00:08 UTC, juperameza commented on app/assets/stylesheets/pages/_crud_employee.css.scss
> +      color: $font-color-gray;
Alphabetically order this

2023-01-26 00:08 UTC, juperameza commented on app/controllers/employees_controller.rb
> +
At this moment everyone can access this page shouldn't you protect it by adding `   before_action :authenticate_user!` or whatever session login that you're using

2023-01-26 00:08 UTC, juperameza commented on app/views/employees/new.html.erb
> +</div>
Add a blank line after this

2023-01-26 01:03 UTC, dagp-ucol approved these changes

2023-01-26 01:53 UTC, juperameza approved these changes
Lgtm

2023-01-26 14:06 UTC, merged