Admin login
BrightCoders-Institute/BCDIC22-RoR-reloj-checador-team2 pull request #41
Opened 2023-02-03 22:54 UTC by EverardoAlcarazBaltazar

# Description

We implement a login form and database for admins, and also linked them because is necessary that only the admins can manage the employee and store table.

## Screenshots

![login](https://user-images.githubusercontent.com/72171554/216726100-3ebfeadf-40ec-4d14-836b-fc7e35833849.JPG)
![Captura](https://user-images.githubusercontent.com/72171554/216726101-0bf08227-cc68-46b8-8c75-5cf82c73d6c1.JPG)

2023-02-03 23:00 UTC, DiegoCoronaBarragan approved these changes

2023-02-03 23:03 UTC, oscaregr approved these changes

2023-02-04 01:52 UTC, JuanequeX requested changes

2023-02-04 01:52 UTC, JuanequeX commented on app/assets/stylesheets/layout/_navbar.css.scss
> +    background-color: #D9D9D9;    ;
Changes for a color variable

2023-02-04 01:52 UTC, JuanequeX commented on app/assets/stylesheets/pages/_report_form.css.scss
> +}
add an space between your class name an your curly braces, and add a blank line between each blocks

2023-02-04 01:52 UTC, JuanequeX commented on app/models/user.rb
> +  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
Delete this comments

2023-02-04 01:52 UTC, JuanequeX commented on app/views/users/confirmations/new.html.erb
> +    <%= f.email_field :email, autofocus: true, autocomplete: "email", value: (resource.pending_reconfirmation? ? resource.unconfirmed_email : resource.email) %>
This line is so long, please refactor it.

2023-02-04 01:52 UTC, JuanequeX commented on app/views/users/mailer/confirmation_instructions.html.erb
> +<p><%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %></p>
I think the tag `p` is unnecessary

2023-02-04 01:52 UTC, JuanequeX commented on app/views/users/mailer/unlock_instructions.html.erb
> +<p><%= link_to 'Unlock my account', unlock_url(@resource, unlock_token: @token) %></p>
I think the tag p is unnecessary

2023-02-04 01:52 UTC, JuanequeX commented on app/views/users/mailer/reset_password_instructions.html.erb
> +<p><%= link_to 'Change my password', edit_password_url(@resource, reset_password_token: @token) %></p>
I think the tag p is unnecessary

2023-02-04 01:52 UTC, JuanequeX commented on app/views/users/registrations/edit.html.erb
> +<% end %>
the use of the `<br>`is a bad practice, please remove it

2023-02-04 01:52 UTC, JuanequeX commented on app/views/users/registrations/new.html.erb
> +    <% end %><br />
Same here with the `<br>`

2023-02-04 01:52 UTC, JuanequeX commented on app/views/users/sessions/new.html.erb
> +    <p class="navbar-text float-right"></p>
what is the reason of put this `p`?

2023-02-04 01:52 UTC, JuanequeX commented on db/seeds.rb
> +User.create!({:email => "iker@gmail.com", :password => "123456", :password_confirmation => "123456" })
Add a blank line at the end of this file

2023-02-07 22:00 UTC, MarcoRodriguez23 approved these changes

2023-02-07 22:11 UTC, JuanequeX requested changes

2023-02-07 22:11 UTC, JuanequeX commented on app/assets/stylesheets/layout/_navbar.css.scss
> +    background-color: #7B7B7B;
Changes for a color variable

2023-02-07 22:11 UTC, JuanequeX commented on app/assets/stylesheets/layout/_navbar.css.scss
> +    color: white;
Changes for a color variable

2023-02-07 22:11 UTC, JuanequeX commented on app/assets/stylesheets/layout/_navbar.css.scss
> +}
Add a blank line at the end of this file

2023-02-07 22:11 UTC, JuanequeX commented on app/assets/stylesheets/pages/_checking_employee.css.scss
> +}
Add a blank line at the end of this file

2023-02-07 22:11 UTC, JuanequeX commented on app/assets/stylesheets/pages/_crud_employee.css.scss
> +}
Add a blank line at the end of this file

2023-02-07 22:11 UTC, JuanequeX commented on app/assets/stylesheets/pages/_crud_store.css.scss
> +}
Add a blank line at the end of this file

2023-02-07 22:11 UTC, JuanequeX commented on app/assets/stylesheets/pages/_login_admin.css.scss
> +}
Add a blank line at the end of this file

2023-02-07 22:11 UTC, JuanequeX commented on app/assets/stylesheets/pages/_register_forms.css.scss
> +}
Add a blank line at the end of this file

2023-02-07 22:11 UTC, JuanequeX commented on app/assets/stylesheets/pages/_report_form.css.scss
> +}
Add a blank line at the end of this file

2023-02-07 22:23 UTC, JuanequeX approved these changes

2023-02-07 22:25 UTC, merged